# config.yml

backend:
  name: github
  repo: JAHqu2zyPA/new_blog # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
media_folder: '/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Tags', name: 'tag', widget: 'string' }
      - { label: 'Thumbnail', name: 'image', widget: 'file' }
      - { label: 'Category', name: 'categories', widget: 'string' }     
      - {label: 'Author',
        name: 'author',
        widget: 'relation',
        collection: 'authors',
        display_fields: [username],
        search_fields: [username],
        value_field: 'title',
      }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'authors'
    label: 'Authors'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
      - { label: 'Short Name', name: 'name', widget: 'string' }
      - { label: 'User Name', name: 'username', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'Website', name: 'website', widget: 'string' }
      - { label: 'Twitter', name: 'twitter', widget: 'string' }
      - { label: 'Facebook', name: 'facebook', widget: 'string' }
      - { label: 'Linkedin', name: 'linkedin', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'string' }    
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Thumbnail', name: 'image', widget: 'file' }

